export const ActionTypes = {
  SET_SERVICES: "SET_SERVICES",
  SELECTED_SERVICE: "SELECTED_SERVICE",
  REMOVE_SELECTED_SERVICE: "REMOVE_SELECTED_SERVICE",
  SET_REQUESTS: "SET_REQUESTS",
  SELECTED_REQUEST: "SELECTED_REQUEST",
};
